# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b49640f67dea0042c01d2d9593184d3ccb95fe2fe0b2a9e3865ad4b8f7a72c3e0076c1e2e63a2738f0d4ca4437be2863cac9c8cc26ddff32a38d29032fdec4

test:
  secret_key_base: 42f3ccf4c2c66ec0cd18b4442292c2048760fde5022f96dd31800ec721ad7f315592ad310308b7df660e646f4657449322c3a7636e78507111979190d52ca726

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
